// Pre-written bilingual server messages (never generated by the LLM). Listed in TRANSLATION_REVIEW.md.
import type { ReplyLanguage } from './language.ts';

type Lang = 'en' | 'ta' | 'tanglish';
type Bundle = Record<Lang, string>;

export const SERVER_MESSAGES = {
  queued: {
    en: "I've saved your message 💛 I'm having trouble thinking right now, so I'll reply properly in a little while. Anything you logged is safe.",
    ta: 'உன் மெசேஜ் சேவ் ஆயிடுச்சு 💛 இப்போ கொஞ்சம் யோசிக்க முடியல, கொஞ்ச நேரத்துல சரியா பதில் சொல்றேன். நீ பதிவு செஞ்சது எல்லாம் பத்திரமா இருக்கு.',
    tanglish: "Un message save aayiduchu 💛 Ippo konjam yosikka mudiyala, konja nerathula sariya reply panren. Nee log pannadhu ellam safe ah iruku.",
  },
  budget: {
    en: "I've saved your message 💛 I've hit my chatting limit for today, so I'll reply as soon as it resets. You can still log things from the Today tab.",
    ta: 'உன் மெசேஜ் சேவ் ஆயிடுச்சு 💛 இன்னைக்கு என் பேசுற லிமிட் முடிஞ்சிடுச்சு, ரீசெட் ஆனதும் பதில் சொல்றேன். Today டேப்ல இருந்து இன்னும் பதிவு பண்ணலாம்.',
    tanglish: "Un message save aayiduchu 💛 Innaiku en chat limit mudinjiduchu, reset aanadhum reply panren. Today tab la irundhu innum log pannalam.",
  },
  rateLimited: {
    en: "That's a lot of messages in a few minutes! Give me a short breather and I'll be right here 💛",
    ta: 'கொஞ்ச நேரத்துல நிறைய மெசேஜ் வந்திருக்கு! ஒரு சின்ன ப்ரேக் குடு, நான் இங்கேயே இருக்கேன் 💛',
    tanglish: 'Konja nerathula neraya messages! Oru chinna break kudu, naan inga dhaan iruken 💛',
  },
  replyReadyTitle: {
    en: 'Companion replied',
    ta: 'Companion பதில் சொல்லியிருக்கு',
    tanglish: 'Companion reply panniruku',
  },
  replyReadyBody: {
    en: 'I finally got back to your message 💛',
    ta: 'உன் மெசேஜுக்கு பதில் சொல்லிட்டேன் 💛',
    tanglish: 'Un message ku reply panniten 💛',
  },
  delayTitle: {
    en: 'Just checking in 💛',
    ta: 'சும்மா விசாரிக்கிறேன் 💛',
    tanglish: 'Summa visarikiren 💛',
  },
  delayBody: {
    en: 'Your period seems a little later than the usual range. Want to talk about it?',
    ta: 'உன் பீரியட் வழக்கமான range-ஐ விட கொஞ்சம் லேட் ஆகுது போல. பேசலாமா?',
    tanglish: 'Un period usual range ah vida konjam late aagudhu pola. Pesalaama?',
  },
  redFlagTitle: {
    en: 'A gentle note',
    ta: 'ஒரு சின்ன குறிப்பு',
    tanglish: 'Oru chinna note',
  },
  redFlagBody: {
    en: "Something you logged is worth showing your doctor. I've put a note in the Cycle tab.",
    ta: 'நீ பதிவு செஞ்ச ஒன்னு டாக்டர்கிட்ட காட்டுறது நல்லது. Cycle டேப்ல ஒரு குறிப்பு வச்சிருக்கேன்.',
    tanglish: 'Nee log panna onnu doctor kitta kaatradhu nalladhu. Cycle tab la oru note vechiruken.',
  },
  weeklyTitle: {
    en: 'Your week with Companion',
    ta: 'இந்த வாரம் உன்னோட',
    tanglish: 'Indha vaaram unnoda',
  },
  softNudge: {
    en: "Haven't heard from you in a few days. No pressure at all, I'm here whenever you want to chat 💛",
    ta: 'சில நாளா உன்கிட்ட இருந்து எதுவும் இல்ல. எந்த அவசரமும் இல்ல, பேசணும்னு தோணும்போது நான் இருக்கேன் 💛',
    tanglish: 'Sila naala un kitta irundhu edhuvum illa. Endha avasaramum illa, pesanum nu thonum podhu naan iruken 💛',
  },
} satisfies Record<string, Bundle>;

// Delay check-in written in code from computed factors (no LLM call, so it costs nothing).
export const FACTOR_PHRASES: Record<string, Bundle> = {
  high_stress: { en: 'quite a few stressful days', ta: 'நிறைய ஸ்ட்ரெஸ்ஸான நாட்கள்', tanglish: 'neraya stress aana naatkal' },
  poor_sleep: { en: 'less sleep than usual', ta: 'வழக்கத்தை விட குறைவான தூக்கம்', tanglish: 'vazhakkatha vida kammiyana thookkam' },
  weight_change: { en: 'a change in weight', ta: 'எடையில் ஒரு மாற்றம்', tanglish: 'weight la oru maatram' },
  exercise_change: { en: 'a big jump in exercise', ta: 'உடற்பயிற்சியில் திடீர் அதிகரிப்பு', tanglish: 'exercise la thideer nu increase' },
  illness_or_travel: { en: 'being unwell or travelling', ta: 'உடம்பு சரியில்லாதது அல்லது பயணம்', tanglish: 'udambu sari illadhadhu illa travel' },
  medication_change: { en: 'a medication starting or stopping', ta: 'மருந்து தொடங்கியது அல்லது நிறுத்தியது', tanglish: 'medicine start/stop pannadhu' },
  low_intake_days: { en: 'some days with lighter meals than your usual', ta: 'சில நாள் வழக்கத்தை விட குறைவா சாப்பிட்டது', tanglish: 'sila naal vazhakkatha vida kammiya saaptadhu' },
  usual_pattern: { en: 'your cycles have been this long before too', ta: 'முன்னாடியும் உன் சைக்கிள் இவ்வளவு நீளமா இருந்திருக்கு', tanglish: 'munnadiyum un cycle ivlo neelama irundhiruku' },
};

export function delayCheckIn(lang: Lang, daysLate: number, factors: string[]): string {
  const list = factors.map((f) => FACTOR_PHRASES[f]?.[lang]).filter(Boolean).join(', ');
  if (lang === 'ta') {
    return `ஹே, உன் பீரியட் கணிச்ச range-ஐ விட ${daysLate} நாள் லேட் ஆகுது போல 💛 PCOS-ல இது சகஜம் தான்.` +
      (list ? ` இதுக்கு காரணமா இருந்திருக்கக்கூடியவை: ${list}.` : '') +
      ' வாய்ப்பு இருந்தா ஒரு pregnancy test எடுத்து பார்க்கிறது ஈஸியான வழி. தொடர்ந்து லேட் ஆனா உன் டாக்டர் உதவுவாங்க. எப்படி இருக்க?';
  }
  if (lang === 'tanglish') {
    return `Hey, un period predict panna range ah vida ${daysLate} naal late aagudhu pola 💛 PCOS la idhu saghajam dhaan.` +
      (list ? ` Idhuku role play pannirukka koodiyavai: ${list}.` : '') +
      ' Possibility irundha oru pregnancy test eduthu paakuradhu easy ah rule out panna help pannum. Continue ah late aana un doctor help pannuvaanga. Epdi iruka?';
  }
  return `Hey, your period looks about ${daysLate} day${daysLate === 1 ? '' : 's'} past the predicted range 💛 That's common with PCOS.` +
    (list ? ` Things that may have played a role: ${list}.` : '') +
    " If there's any chance of pregnancy, a home test is an easy way to rule that out. If delays keep happening, your doctor can help. How are you feeling?";
}

export function pick(bundle: Bundle, lang: ReplyLanguage | 'auto' | null | undefined): string {
  if (lang === 'ta') return bundle.ta;
  if (lang === 'tanglish') return bundle.tanglish;
  if (lang === 'mixed') return `${bundle.tanglish}\n${bundle.ta}`;
  if (lang === 'en') return bundle.en;
  // Unknown: bilingual (English + Tamil)
  return `${bundle.en}\n${bundle.ta}`;
}
