// Rebuilds src/store/seed/llm-models.json from OpenRouter's live list: the 10 best current `:free` models.
// Run: npm run models:seed   (no API key needed; the models endpoint is public). The backend syncs this file
// into the database on startup. Then run npm run models:eval to tag Tamil / Tanglish-capable models.
import { writeFileSync } from 'node:fs';

interface OrModel {
  id: string;
  name: string;
  created: number;
  context_length: number;
  architecture?: { input_modalities?: string[] };
  supported_parameters?: string[];
}

// Families that have handled Tamil/Tanglish reasonably get a small boost; language-eval re-checks everything.
const PREFERRED = [/gemini/i, /gemma-3/i, /deepseek/i, /llama-4/i, /llama-3\.3-70b/i, /qwen3/i, /mistral-small/i, /kimi/i, /glm/i, /gpt-oss/i];

async function main() {
  const res = await fetch('https://openrouter.ai/api/v1/models');
  if (!res.ok) throw new Error(`OpenRouter returned ${res.status}`);
  const { data } = (await res.json()) as { data: OrModel[] };
  const free = data.filter((m) => m.id.endsWith(':free') && m.context_length >= 16000);
  const scored = free
    .map((m) => {
      const pref = PREFERRED.findIndex((re) => re.test(m.id));
      const json = m.supported_parameters?.includes('response_format') ?? false;
      return { m, json, vision: m.architecture?.input_modalities?.includes('image') ?? false, score: (pref === -1 ? 0 : 20 - pref) + (json ? 5 : 0) + Math.min(m.created / 1e8, 20) };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, 10);
  if (scored.length === 0) throw new Error('No :free models found');
  if (!scored.some((s) => s.vision)) {
    const v = free.find((m) => m.architecture?.input_modalities?.includes('image'));
    if (v) scored[scored.length - 1] = { m: v, json: !!v.supported_parameters?.includes('response_format'), vision: true, score: 0 };
  }
  const models = scored.map((s, i) => ({
    model_id: s.m.id,
    priority: i + 1,
    caps: ['chat', 'json', ...(s.vision ? ['vision'] : [])],
    enabled: true,
    supports_response_format: s.json,
    notes: `${s.m.name}; seeded ${new Date().toISOString().slice(0, 10)}; run language-eval`,
  }));
  const out = { _about: [`Generated by scripts/seed-models.ts on ${new Date().toISOString()} from the live OpenRouter list.`, 'tamil_script / tanglish caps are added by scripts/language-eval.ts --apply.'], models };
  writeFileSync('src/store/seed/llm-models.json', `${JSON.stringify(out, null, 1)}\n`);
  console.log(models.map((m) => `${m.priority}. ${m.model_id} [${m.caps.join(',')}]`).join('\n'));
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
