/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in user and her profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfilePatch"];
                };
            };
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Onboarding"];
                };
            };
            responses: {
                /** @description Onboarding saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Messages, oldest first (the latest page, or older than `before`) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatList"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessage"];
                };
            };
            responses: {
                /** @description Reply, or a queued notice if no model is available right now */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UndoLogRequest"];
                };
            };
            responses: {
                /** @description The log was removed (or restored, for water/sleep/exercise) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageUpdated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/confirm-period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeriodChipRequest"];
                };
            };
            responses: {
                /** @description Period start/end logged from a confirm chip */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageUpdated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/undo-period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeriodChipRequest"];
                };
            };
            responses: {
                /** @description A confirmed period chip was undone */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageUpdated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/food/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoRequest"];
                };
            };
            responses: {
                /** @description Detected items (not saved) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/food/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogFoods"];
                };
            };
            responses: {
                /** @description Saved through the same food pipeline as chat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoodLogs"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/food/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    day?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One day's logs with the server-computed balance score and cycle status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Today"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Water"];
                };
            };
            responses: {
                /** @description Water updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/quick-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuickLog"];
                };
            };
            responses: {
                /** @description Logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Weight"];
                };
            };
            responses: {
                /** @description Weight saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Periods, the predicted range and active cycle insights */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cycle"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycle/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogPeriod"];
                };
            };
            responses: {
                /** @description Period start or end logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Period"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycle/periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeriodPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Period"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/meds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All medicines (active first) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Medications"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MedInput"];
                };
            };
            responses: {
                /** @description Added */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Medication"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MedPatch"];
                };
            };
            responses: {
                /** @description Updated. Setting active=false records the stop date (it counts as a medication change for delay insights). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Medication"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/meds/{id}/dose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DoseTaken"];
                };
            };
            responses: {
                /** @description Dose marked taken / not taken */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lab results, oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Labs"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LabInput"];
                };
            };
            responses: {
                /** @description Added */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lab"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active remembered facts, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Facts"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forgotten */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FactPatch"];
                };
            };
            responses: {
                /** @description Edited */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fact"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trends and insight cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Insights"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dismissed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PushSubscription"];
                };
            };
            responses: {
                /** @description Saved for this device */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PushEndpoint"];
                };
            };
            responses: {
                /** @description Removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sends a test notification to her devices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PushTestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/med-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MedAction"];
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "x-cron-secret"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runs due jobs: reminders + retries every call; daily/weekly jobs once per period */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "x-cron-secret"?: string;
                };
                path: {
                    name: "reminders" | "retry-queue" | "cycle-check" | "daily-summary" | "model-health";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runs one job now (manual trigger) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            result?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {boolean} */
            ok: true;
            version: string;
            /** @enum {string} */
            store: "memory" | "mongo";
        };
        Me: {
            uid: string;
            email: string | null;
            profile: components["schemas"]["Profile"];
        };
        Profile: {
            companion_name: string;
            /** @enum {string} */
            display_language: "auto" | "en" | "ta" | "tanglish";
            /** @enum {string} */
            ui_language: "en" | "ta";
            /** @enum {string} */
            persona_tone: "bestie" | "calm" | "coach";
            /** @enum {string} */
            tamil_address_form: "casual" | "respectful";
            /** @enum {string} */
            calorie_display: "show" | "hide";
            goals: string[];
            diet_type: string | null;
            allergies: string[];
            typical_cycle_length: number | null;
            onboarding_done: boolean;
            timezone: string;
            morning_checkin: string;
            evening_checkin: string;
            quiet_start: string;
            quiet_end: string;
            water_nudges: boolean;
            weight_tracking: boolean;
        };
        ProfilePatch: {
            companion_name?: string;
            /** @enum {string} */
            display_language?: "auto" | "en" | "ta" | "tanglish";
            /** @enum {string} */
            ui_language?: "en" | "ta";
            /** @enum {string} */
            persona_tone?: "bestie" | "calm" | "coach";
            /** @enum {string} */
            tamil_address_form?: "casual" | "respectful";
            /** @enum {string} */
            calorie_display?: "show" | "hide";
            goals?: string[];
            diet_type?: string | null;
            allergies?: string[];
            typical_cycle_length?: number | null;
            timezone?: string;
            morning_checkin?: string;
            evening_checkin?: string;
            quiet_start?: string;
            quiet_end?: string;
            water_nudges?: boolean;
            weight_tracking?: boolean;
        };
        Onboarding: {
            profile: {
                companion_name?: string;
                /** @enum {string} */
                display_language?: "auto" | "en" | "ta" | "tanglish";
                /** @enum {string} */
                ui_language?: "en" | "ta";
                /** @enum {string} */
                persona_tone?: "bestie" | "calm" | "coach";
                /** @enum {string} */
                tamil_address_form?: "casual" | "respectful";
                /** @enum {string} */
                calorie_display?: "show" | "hide";
                goals?: string[];
                diet_type?: string | null;
                allergies?: string[];
                typical_cycle_length?: number | null;
                timezone?: string;
                morning_checkin?: string;
                evening_checkin?: string;
                quiet_start?: string;
                quiet_end?: string;
                water_nudges?: boolean;
                weight_tracking?: boolean;
            };
            medications: components["schemas"]["MedInput"][];
            last_period_start: string | null;
        };
        MedInput: {
            name: string;
            dose: string | null;
            schedule_times: string[];
        };
        ChatList: {
            messages: components["schemas"]["ChatMessage"][];
            has_more: boolean;
        };
        ChatMessage: {
            id: string;
            created_at: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** @enum {string} */
            status: "pending" | "done" | "queued" | "failed";
            meta: components["schemas"]["MessageMeta"];
        };
        MessageMeta: {
            reply_to?: string;
            logs?: {
                /** @enum {string} */
                table: "food_logs" | "symptom_logs" | "mood_logs" | "med_intake" | "lifestyle_logs";
                id: string;
                label: string;
            }[];
            pending?: {
                /** @enum {string} */
                kind: "period_start" | "period_end";
                date: string;
                /** @enum {string|null} */
                flow: "spotting" | "light" | "medium" | "heavy" | null;
                pain: number | null;
            }[];
            flags?: {
                crisis: boolean;
                red_flag: boolean;
            };
            fallback?: boolean;
            kind?: string;
            undone?: {
                [key: string]: boolean;
            };
            confirmed?: {
                [key: string]: string;
            };
        };
        SendResult: {
            /** @enum {string} */
            status: "done" | "queued";
            message: components["schemas"]["ChatMessage"];
            reply: components["schemas"]["ChatMessage"] | null;
            notice: components["schemas"]["ChatMessage"] | null;
            crisis: boolean;
        };
        SendMessage: {
            text: string;
            /** Format: uuid */
            client_id: string;
        };
        MessageUpdated: {
            message: components["schemas"]["ChatMessage"];
        };
        UndoLogRequest: {
            message_id: string;
            log_id: string;
        };
        PeriodChipRequest: {
            message_id: string;
            index: number;
        };
        PhotoResult: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            is_food: boolean;
            items: {
                name: string;
                quantity: number | null;
                unit: string | null;
                estimated_grams: number | null;
            }[];
        };
        PhotoRequest: {
            image_base64: string;
            /**
             * @default null
             * @enum {string|null}
             */
            meal: "breakfast" | "lunch" | "snack" | "dinner" | "other" | null;
        };
        FoodLogs: {
            logs: components["schemas"]["FoodLog"][];
        };
        FoodLog: {
            id: string;
            day: string;
            /** @enum {string} */
            meal: "breakfast" | "lunch" | "snack" | "dinner" | "other";
            item_name: string;
            quantity: number | null;
            unit: string | null;
            grams: number | null;
            kcal: number | null;
            protein_g: number | null;
            carbs_g: number | null;
            fiber_g: number | null;
            added_sugar_g: number | null;
            veg_g: number | null;
            /** @enum {string} */
            gi_band: "low" | "medium" | "high" | "unknown";
            is_estimate: boolean;
            /** @enum {string} */
            source: "text" | "photo" | "manual";
        };
        LogFoods: {
            items: {
                name: string;
                quantity: number | null;
                unit: string | null;
                /** @default null */
                grams: number | null;
            }[];
            /** @enum {string} */
            meal: "breakfast" | "lunch" | "snack" | "dinner" | "other";
            day: string;
            /** @enum {string} */
            source: "photo" | "manual";
        };
        Ok: {
            /** @enum {boolean} */
            ok: true;
        };
        Today: {
            day: string;
            /** @enum {string} */
            calorie_display: "show" | "hide";
            status: components["schemas"]["CycleStatus"];
            prediction: components["schemas"]["Prediction"];
            foods: components["schemas"]["FoodLog"][];
            score: components["schemas"]["Score"];
            moods: {
                id: string;
                mood: number | null;
                energy: number | null;
                stress: number | null;
            }[];
            symptoms: {
                id: string;
                symptom: string;
                severity: number;
            }[];
            lifestyle: {
                water_ml: number | null;
                sleep_hours: number | null;
                exercise_minutes: number | null;
                steps: number | null;
            } | null;
            meds: {
                medication: components["schemas"]["Medication"];
                doses: components["schemas"]["Dose"][];
            }[];
            weight_due: boolean;
        };
        CycleStatus: {
            /** @enum {string} */
            kind: "none" | "period" | "cycle" | "late";
            cycle_day: number | null;
            period_day: number | null;
            days_late: number | null;
            /** @enum {string|null} */
            phase: "menstrual" | "follicular" | "luteal" | "late" | "unknown" | null;
        };
        Prediction: {
            earliest: string;
            likely: string;
            latest: string;
            /** @enum {string} */
            confidence: "low" | "medium" | "high";
            cycles_used: number;
        } | null;
        Score: {
            score: number;
            highlights: ("protein" | "fiber" | "low_gi" | "low_sugar" | "veggies")[];
            /** @enum {string|null} */
            idea: "add_protein" | "add_fiber" | "add_veggies" | "swap_low_gi" | null;
            kcal: number | null;
        } | null;
        Medication: {
            id: string;
            name: string;
            dose: string | null;
            schedule_times: string[];
            active: boolean;
            start_date: string | null;
            end_date: string | null;
        };
        Dose: {
            time: string;
            taken: boolean;
        };
        Water: {
            day: string;
            ml: number;
        };
        QuickLog: {
            day: string;
            mood?: number | null;
            energy?: number | null;
            stress?: number | null;
            symptoms?: ("acne" | "hair_fall" | "hirsutism" | "bloating" | "cramps" | "cravings" | "fatigue" | "headache" | "pelvic_pain" | "breast_tenderness" | "spotting" | "fainting" | "other")[];
            sleep_hours?: number | null;
        };
        Weight: {
            day: string;
            weight_kg: number;
        };
        Cycle: {
            today: string;
            status: components["schemas"]["CycleStatus"];
            prediction: components["schemas"]["Prediction"];
            periods: components["schemas"]["Period"][];
            insights: components["schemas"]["Insight"][];
        };
        Period: {
            id: string;
            start_date: string;
            end_date: string | null;
            /** @enum {string|null} */
            flow: "spotting" | "light" | "medium" | "heavy" | null;
            pain: number | null;
            auto_closed: boolean;
            length_days: number;
            cycle_length: number | null;
        };
        Insight: {
            id: string;
            day: string;
            /** @enum {string} */
            type: "delay" | "weekly" | "red_flag" | "pattern";
            payload: {
                [key: string]: unknown;
            };
            dismissed: boolean;
        };
        LogPeriod: {
            /** @enum {string} */
            kind: "start" | "end";
            date: string;
            /** @enum {string|null} */
            flow?: "spotting" | "light" | "medium" | "heavy" | null;
            pain?: number | null;
        };
        PeriodPatch: {
            end_date?: string | null;
            /** @enum {string|null} */
            flow?: "spotting" | "light" | "medium" | "heavy" | null;
            pain?: number | null;
            /** @enum {boolean} */
            auto_closed?: false;
        };
        Medications: {
            medications: components["schemas"]["Medication"][];
        };
        MedPatch: {
            name?: string;
            dose?: string | null;
            schedule_times?: string[];
            active?: boolean;
        };
        DoseTaken: {
            day: string;
            time: string;
            taken: boolean;
        };
        Labs: {
            labs: components["schemas"]["Lab"][];
        };
        Lab: {
            id: string;
            test_date: string;
            /** @enum {string} */
            test_name: "testosterone" | "AMH" | "LH" | "FSH" | "fasting_insulin" | "HbA1c" | "TSH" | "vitamin_D" | "other";
            test_label: string | null;
            value: number;
            unit: string | null;
            reference_range: string | null;
            within_range: boolean | null;
        };
        LabInput: {
            test_date: string;
            /** @enum {string} */
            test_name: "testosterone" | "AMH" | "LH" | "FSH" | "fasting_insulin" | "HbA1c" | "TSH" | "vitamin_D" | "other";
            test_label: string | null;
            value: number;
            unit: string | null;
            reference_range: string | null;
        };
        Facts: {
            facts: components["schemas"]["Fact"][];
        };
        Fact: {
            id: string;
            fact: string;
            /** @enum {string} */
            category: "preference" | "person" | "event" | "health" | "other";
            updated_at: string;
        };
        FactPatch: {
            fact: string;
        };
        Insights: {
            insights: components["schemas"]["Insight"][];
            cycle_lengths: number[];
            balance_trend: {
                day: string;
                value: number;
            }[];
            mood_trend: {
                day: string;
                value: number;
            }[];
            weight_trend: {
                day: string;
                value: number;
            }[] | null;
            week: {
                days_with_food_logged: number;
                avg_balance_score: number | null;
                avg_mood: number | null;
                avg_sleep_hours: number | null;
                exercise_minutes_total: number;
                medication_doses_taken: number;
            };
        };
        PushSubscription: {
            /** Format: uri */
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
        };
        PushEndpoint: {
            /** Format: uri */
            endpoint: string;
        };
        PushTestResult: {
            result: string;
        };
        MedAction: {
            token: string;
            /** @enum {string} */
            action: "taken" | "snooze";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
